# handler for exceptions /Exception handler. except clause.
# If exception occurs, the except clause is executed and the program continues. If no exception occurs, the except clause is skipped.
# If an exception occurs and type of exception does not match the exception named in the except clause, the exception is passed on to outer try statements. If no handler is found, then
# it is an unhandled exception and the execution is stopped with the message. Here 'Handler' is a block of code designed to handle the exception i.e. try-except construct.

# Exception 0 -
# def foo():
#     while True:
#         try:
#             inp=int(input("Enter a number: "))
#             break
#         except (ValueError, KeyboardInterrupt, EOFError) :
#             print("re enter the input again")
#     print(f"received value from user {inp}")


# Exception 1 -
# def foo():
#     try:
#         return 1
#     finally:
#         return 2

# result = foo()
# print(result)

# TODO vgankidi - read from 'A class in except class' here.

# BaseException is base class of all exceptions. And one subclass Exception
# is base class of not fatal execptions. Class inside an except clause matches
# exception of that class and subclass instances. The except clause derived class
# does not match base class instances.

# Exception 2 - 
# class B(Exception):
#     pass

# class C(B):
#     pass

# class D(C):
#     pass

# # enumberate over class instances and raise exception.
# for cls in [B, C, D]:
#     try:
#         raise cls()
#     except D:
#         print("D")
#     except C:
#         print("C")
#     except B:
#         print("B")

# # We can raise exception with arguments. type of arguments is an object.
# # we can use a variable to after exception name to hold the exception object.
# # and the args variable holds the arguments passed to the exception class.
# # Exception 3 -
# try:
#     raise Exception('a','b')
# except Exception as e:
#     print(type(e))
#     print(e.args)
#     print(e.__str__())

# Exception 4 - TODO @vgankidi.
# import sys

# def test():
# 	try:
# 		f = open('myfile.txt')
# 		s = f.readline()
# 		i = int(s.strip())
# 	except OSError as err: # err attribute holds the OSError object.
# 		print("OS error:", err) # err prints the __str()__ method of the OSError object. Which is dervied fromt the Exception base class.
# 	except ValueError:
# 		print("Could not convert data to an integer.")
# 	except Exception as a: # what does this 3 lines of code here do?
# 		print(f"Unexpected {a=}, {type(a)=}")
# 		raise

# Exception 5 - Else clause (what is the use).

# for arg in sys.argv[1:]:
#     try:
#         f = open(arg, 'r')
#     except OSError:
#         print('cannot open', arg)
#     else:
#         print(arg, 'has', len(f.readlines()), 'lines')
#         f.close()

# Raising Exceptions - use the raise keyword, The exception should be an Exception class or
# instance of the Exception class. The class after raise keyword should be dervied from the 
# baseException class or the Exception class or Exception class itself. we can re raise the
# exception after we handled the exception using raise to let the user know that something
# unexpected has happened (after handling any clean up actions if required). If we pass exception
# class as an argument to raise statement, it will be instantiated implicitly by calling cnstructor
# without arguments.
# try:
#     raise NameError('HiThere')
# except NameError as err:
#     print('an exception happened' , err)
#     raise # re raise the exception.

# Exception Chaining - If unexpected exception occurs during handling of the exception, 
# the exception handler block is logged along with the unhandled exception. In the example
# below, the unhandled exception is generated by raise statement and followed by exception subclass.

# try:
#     fp=open('myfile.txt','r')
# except FileNotFoundError as err:
#     print('handle the exception here')
#     raise OSError # raising OSError error an example for exception.

# User defined exceptions.
# 


# Definig Clean-up Actions (Exceptions - finally block)
# The finally clause will execute as last task before the try statement completes. When is try statement complete?
# from decimal import DivisionByZero


# def TryFinal():
#     try:
#         print('executing try')
#         sys.exit
#         print('try after sys exit')
#         return True
#     finally:
#         print('finally')
#         return False

# Handling exceptions properly will not expose the source code to the
# users in the logs. We can use the logging module for logging. In morgan
# stanley when we encountered code in the logs, They added exceptions to
# handle those scnearios. I.e. All unknown or undefined exceptions are 
# caught using the default exception handler. So In order to test, we need
# to know what exceptions are being handled by the application (And definition
# so the test data can be prepared). In the below example, we can test using the
# argument y being 0. And the type of the arguments string as test data for 
# negative cases. Using this we can check if the exceptions are handled correctly in
# the application.
# def divide(x, y):
#     try:
#         result = x/y
#     except (ZeroDivisionError, TypeError) as err:
#         print(f"Error encoutered ${err.__str__()}")
#     else:
#         print(f"result is ${result}")
#     finally:
#         print("Executing the finally block")

# Predefined Clean up Actions

# Raising and Handling Multipe Unrelated Exceptions

# Exception can be handled outside the function definition. And,
# similar type of multiple exceptions can be raised.
# first try block statement is executed, if there is Exception then
# we raise the exception and exception handler handles the exception
# And, we continue with the execution of statements after the try/except
# block.

# def test_exce(text):
#     if "hello" in text:
#         raise NameError("hello is not allowed")
#     elif "txt" in text:
#         raise NameError("txt is not allowed")

# for item in ["hello txt", "txt"]:
#     try:
#         test_exce("hello txt")
#     except NameError as err:
#         print(err)

